# Generated by Django 6.1.1 on 2026-09-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
