# Generated by Django 6.1.1 on 2026-09-26 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_users_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Validate',
            fields=[
                ('id_user_validate', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('VERIFIKASI', 'verifikasi'), ('NOT VERIFIKASI', 'not verifikasi')], default='NOT VERIFIKASI')),
                ('expired_at', models.DateTimeField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='authentication.users')),
            ],
            options={
                'db_table': 'users_validate',
            },
        ),
    ]
