# Generated by Django 6.1.1 on 2026-09-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_users_validate'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_validate',
            name='kode',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
