# Generated by Django 6.1.1 on 2026-09-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_users_validate_kode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_validate',
            old_name='id_user',
            new_name='email',
        ),
    ]
