# Generated by Django 6.1.1 on 2026-09-27 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_id_user_users_validate_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_validate',
            old_name='email',
            new_name='id_user',
        ),
    ]
